import { CONSTANTS__NAMES_BANKS } from 'src/asset/utils/isoBanks';

export const banksMyfin = [
  { name: CONSTANTS__NAMES_BANKS.ALFA, localId: 14 },
  { name: CONSTANTS__NAMES_BANKS.BELARUSBANK, localId: 24 },
  { name: CONSTANTS__NAMES_BANKS.BELWEB, localId: 26 },
  { name: CONSTANTS__NAMES_BANKS.BELGAZPROM, localId: 28 },
  { name: CONSTANTS__NAMES_BANKS.BELINVEST, localId: 30 },
  { name: CONSTANTS__NAMES_BANKS.BSB, localId: 36 },
  { name: CONSTANTS__NAMES_BANKS.BNB, localId: 32 },
  { name: CONSTANTS__NAMES_BANKS.BTA, localId: 40 },
  { name: CONSTANTS__NAMES_BANKS.DABRABYT, localId: 20 },
  { name: CONSTANTS__NAMES_BANKS.RRB, localId: 58 },
  { name: CONSTANTS__NAMES_BANKS.BELAGRO, localId: 22 },
  { name: CONSTANTS__NAMES_BANKS.RESHENIE, localId: 66 },
  { name: CONSTANTS__NAMES_BANKS.VTB, localId: 18 },
  { name: CONSTANTS__NAMES_BANKS.MTB, localId: 52 },
  { name: CONSTANTS__NAMES_BANKS.PRIOR, localId: 56 },
  { name: CONSTANTS__NAMES_BANKS.SBER, localId: 38 },
  { name: CONSTANTS__NAMES_BANKS.PARITET, localId: 54 },
  { name: CONSTANTS__NAMES_BANKS.STATUS, localId: 50 },
  { name: CONSTANTS__NAMES_BANKS.TECHNO, localId: 62 },
  { name: CONSTANTS__NAMES_BANKS.TK, localId: 64 },
  { name: CONSTANTS__NAMES_BANKS.CEPTER, localId: 72 },
];
