export const CONSTANTS__NAMES_BANKS = {
  ALFA: 'ALFA',
  BELWEB: 'BELWEB',
  VTB: 'VTB',
  DABRABYT: 'DABRABYT',
  RESHENIE: 'RESHENIE',
  BELAGRO: 'BELAGRO',
  BELARUSBANK: 'BELARUSBANK',
  BELGAZPROM: 'BELGAZPROM',
  BELINVEST: 'BELINVEST',
  BNB: 'BNB',
  BSB: 'BSB',
  BTA: 'BTA',
  MTB: 'MTB',
  PARITET: 'PARITET',
  PRIOR: 'PRIOR',
  RRB: 'RRB',
  SBER: 'SBER',
  STATUS: 'STATUS',
  TECHNO: 'TECHNO',
  EXPERT: 'INCASS-EXPERT',
  TK: 'TK',
  CEPTER: 'CEPTER',
};
export const mockBanks = [
  {
    idbank: 1,
    codename: CONSTANTS__NAMES_BANKS.ALFA,
    logo: 'https://www.sostav.ru/images/news/2019/05/08/wwh5l7ed.png',
    name: 'Альфа Банк',
  },
  {
    idbank: 2,
    codename: CONSTANTS__NAMES_BANKS.BELARUSBANK,
    logo: 'https://select.by/uploads/static/belarusbank-2017-09-20.gif',
    name: 'Беларусьбанк',
  },
  {
    idbank: 3,
    codename: CONSTANTS__NAMES_BANKS.BELAGRO,
    logo: 'https://magnit-tc.by/wp-content/uploads/2016/09/belagro-700x460.png',
    name: 'Белагропромбанк',
  },
  {
    idbank: 4,
    codename: CONSTANTS__NAMES_BANKS.BELGAZPROM,
    logo: 'https://belgazprombank.by/uploads/userfiles/images/logorus.png',
    name: 'Белгазпромбанк',
  },
  {
    idbank: 5,
    codename: CONSTANTS__NAMES_BANKS.BELINVEST,
    logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIGwWWSLLWu1JJmPoX9sjtTIkqBkEmhdn69fehZxM3Vg&s',
    name: 'Белинвестбанк',
  },
  {
    idbank: 6,
    codename: CONSTANTS__NAMES_BANKS.BELWEB,
    logo: 'https://www.belta.by/images/storage/news/with_archive/2019/000021_1560842297_74_big.jpg',
    name: 'Банк БелВеб',
  },
  {
    idbank: 7,
    codename: CONSTANTS__NAMES_BANKS.BNB,
    logo: 'https://bnb.by/upload/iblock/4db/4db4080ca40e1df9b59b598808f5e9e3.jpg',
    name: 'БНБ Банк',
  },
  {
    idbank: 8,
    codename: CONSTANTS__NAMES_BANKS.BSB,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/74/%D0%91%D0%A1%D0%91%D0%91%D0%B0%D0%BD%D0%BA.png',
    name: 'БСБ Банк',
  },
  {
    idbank: 9,
    codename: CONSTANTS__NAMES_BANKS.BTA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/55/BTA_Logo.gif',
    name: 'БТА Банк',
  },
  {
    idbank: 10,
    codename: CONSTANTS__NAMES_BANKS.CEPTER,
    logo: 'https://creditportal.by/images/logos/banks/tsepter-bank_1680.jpg',
    name: 'Цептер Банк',
  },
  {
    idbank: 11,
    codename: CONSTANTS__NAMES_BANKS.DABRABYT,
    logo: 'https://online.bankdabrabyt.by/resources/img/logo.webp?pfdrid_c=true',
    name: 'Банк Дабрабыт',
  },
  {
    idbank: 12,
    codename: CONSTANTS__NAMES_BANKS.MTB,
    logo: 'https://www.mtbank.by/upload/images/services/Logo_Product_services_MB_300x300.png',
    name: 'МТБ Банк',
  },
  {
    idbank: 13,
    codename: CONSTANTS__NAMES_BANKS.PARITET,
    logo: 'https://creditportal.by/images/virtuemart/manufacturer/paritetbank.png',
    name: 'Паритет Банк',
  },
  {
    idbank: 14,
    codename: CONSTANTS__NAMES_BANKS.PRIOR,
    logo: 'https://frgrf.net/d/220416_wsv_priorbank_logotip3.png',
    name: 'Приорбанк',
  },
  {
    idbank: 15,
    codename: CONSTANTS__NAMES_BANKS.RESHENIE,
    logo: 'https://rbank.by/upload/og_image.jpg',
    name: 'Банк Решение',
  },
  {
    idbank: 16,
    codename: CONSTANTS__NAMES_BANKS.RRB,
    logo: 'https://www.aidapioneer.by/upload/iblock/5ee/5ee725bcd38654bd7e4c2c444fd03ec1.jpg',
    name: 'Банк РРБ',
  },
  {
    idbank: 17,
    codename: CONSTANTS__NAMES_BANKS.SBER,
    logo: 'https://assets.turbologo.ru/blog/ru/2020/02/18161759/logo-sber.png',
    name: 'Сбер Банк',
  },
  {
    idbank: 18,
    codename: CONSTANTS__NAMES_BANKS.STATUS,
    logo: 'https://kidsmebel.by/image/data/image_20.png',
    name: 'Статус Банк',
  },
  {
    idbank: 19,
    codename: CONSTANTS__NAMES_BANKS.TECHNO,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/%D0%9B%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF_%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D0%B8_%D0%A2%D0%B5%D1%85%D0%BD%D0%BE%D0%B1%D0%B0%D0%BD%D0%BA.png',
    name: 'Техно Банк',
  },
  {
    idbank: 20,
    codename: CONSTANTS__NAMES_BANKS.TK,
    logo: 'https://creditportal.by/images/virtuemart/manufacturer/tkbank.png',
    name: 'ТК Банк',
  },
  {
    idbank: 21,
    codename: CONSTANTS__NAMES_BANKS.VTB,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/VTB_logo_2018.png',
    name: 'ВТБ Банк',
  },
  {
    idbank: 22,
    codename: CONSTANTS__NAMES_BANKS.EXPERT,
    logo: 'https://sun9-41.userapi.com/s/v1/if1/NPefGlA93cZpqlTPERa1lzJ2AF8f-FaWuNxAgo1jHxBlNxUeLrr5APWdMVLcnzONGfVus9eI.jpg?size=200x200&quality=96&crop=0,0,738,738&ava=1',
    name: 'Инкасс-Эксперт',
  },
];
export const CONSTANS__TYPE_MONEY = {
  EUR: 'евро',
  USD: 'доллар США',
  RUB: 'российских рублей',
};
